apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "curator.fullname" . }}-config
  labels:
    app: {{ template "curator.name" . }}
    chart: {{ template "curator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: filebeat-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: {{ .Values.unit }}
          unit_count: {{ .Values.unitCount }}
          exclude:
  config.yml: |-
    ---
    client:
      hosts:
        - {{ .Values.global.elasticsearch.host }}
      port: {{ .Values.global.elasticsearch.port }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']