apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filebeat.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
